#!/bin/bash -eu
#
# The contents of this file are subject to the terms of the Common Development and
# Distribution License (the License). You may not use this file except in compliance with the
# License.
#
# You can obtain a copy of the License at legal/CDDLv1.1.txt. See the License for the
# specific language governing permission and limitations under the License.
#
# When distributing Covered Software, include this CDDL Header Notice in each file and include
# the License file at legal/CDDLv1.1.txt. If applicable, add the following below the CDDL
# Header, with the fields enclosed by brackets [] replaced by your own identifying
# information: "Portions copyright [year] [name of copyright owner]".
#
# Copyright 2025 Wren Security
#

#
# Simple Wren:AM SSO Admin Tools wrapper script that initializes and calls the correct `ssoadm`
# executable based on the environment variables.
#

# Wren:AM servlet context path (DEPLOYMENT_URI configuration parameter)
WRENAM_DEPLOYMENT_URI=${WRENAM_DEPLOYMENT_URI:-/auth}

# Path to the target ssoadm executable
WRENAM_SSOADM_EXEC="/opt/ssoadm${WRENAM_DEPLOYMENT_URI}/bin/ssoadm"

# Allow for lazy ssoadm initialization
if [[ ! -f "$WRENAM_SSOADM_EXEC" ]]; then
  echo "[INIT] Configuring SSO Admin Tools..."
  pushd /opt/ssoadm
  ./setup --path $WRENAM_BASE_DIR --acceptLicense
  popd
fi 

"/opt/ssoadm${WRENAM_DEPLOYMENT_URI}/bin/ssoadm" "$@"
